//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio.ServiceCesfam {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Capa.Entities")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Cod_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Tipo_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cod_User {
            get {
                return this.Cod_UserField;
            }
            set {
                if ((this.Cod_UserField.Equals(value) != true)) {
                    this.Cod_UserField = value;
                    this.RaisePropertyChanged("Cod_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tipo_User {
            get {
                return this.Tipo_UserField;
            }
            set {
                if ((this.Tipo_UserField.Equals(value) != true)) {
                    this.Tipo_UserField = value;
                    this.RaisePropertyChanged("Tipo_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCesfam.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidarUsuario", ReplyAction="http://tempuri.org/IServicio/ValidarUsuarioResponse")]
        bool ValidarUsuario(string usu, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidarUsuario", ReplyAction="http://tempuri.org/IServicio/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usu, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateUser", ReplyAction="http://tempuri.org/IServicio/CreateUserResponse")]
        bool CreateUser(decimal cod, string userName, string Pass, decimal type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateUser", ReplyAction="http://tempuri.org/IServicio/CreateUserResponse")]
        System.Threading.Tasks.Task<bool> CreateUserAsync(decimal cod, string userName, string Pass, decimal type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateUSer", ReplyAction="http://tempuri.org/IServicio/UpdateUSerResponse")]
        string UpdateUSer(decimal cod, string userName, string Pass, decimal type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateUSer", ReplyAction="http://tempuri.org/IServicio/UpdateUSerResponse")]
        System.Threading.Tasks.Task<string> UpdateUSerAsync(decimal cod, string userName, string Pass, decimal type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ReadUser", ReplyAction="http://tempuri.org/IServicio/ReadUserResponse")]
        WebPortafolio.ServiceCesfam.Usuario ReadUser(decimal cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ReadUser", ReplyAction="http://tempuri.org/IServicio/ReadUserResponse")]
        System.Threading.Tasks.Task<WebPortafolio.ServiceCesfam.Usuario> ReadUserAsync(decimal cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DeleteUser", ReplyAction="http://tempuri.org/IServicio/DeleteUserResponse")]
        bool DeleteUser(decimal id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DeleteUser", ReplyAction="http://tempuri.org/IServicio/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(decimal id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearFuncionario", ReplyAction="http://tempuri.org/IServicio/CrearFuncionarioResponse")]
        bool CrearFuncionario(decimal cod, string nombre, string paterno, string materno, string direccion, decimal telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearFuncionario", ReplyAction="http://tempuri.org/IServicio/CrearFuncionarioResponse")]
        System.Threading.Tasks.Task<bool> CrearFuncionarioAsync(decimal cod, string nombre, string paterno, string materno, string direccion, decimal telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DeleteFuncionario", ReplyAction="http://tempuri.org/IServicio/DeleteFuncionarioResponse")]
        bool DeleteFuncionario(decimal id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DeleteFuncionario", ReplyAction="http://tempuri.org/IServicio/DeleteFuncionarioResponse")]
        System.Threading.Tasks.Task<bool> DeleteFuncionarioAsync(decimal id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearMedicamento", ReplyAction="http://tempuri.org/IServicio/CrearMedicamentoResponse")]
        bool CrearMedicamento(int id, string nombre, string nomGenerico, System.DateTime fec_vencimiento, string laboratorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearMedicamento", ReplyAction="http://tempuri.org/IServicio/CrearMedicamentoResponse")]
        System.Threading.Tasks.Task<bool> CrearMedicamentoAsync(int id, string nombre, string nomGenerico, System.DateTime fec_vencimiento, string laboratorio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : WebPortafolio.ServiceCesfam.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<WebPortafolio.ServiceCesfam.IServicio>, WebPortafolio.ServiceCesfam.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string usu, string pas) {
            return base.Channel.ValidarUsuario(usu, pas);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usu, string pas) {
            return base.Channel.ValidarUsuarioAsync(usu, pas);
        }
        
        public bool CreateUser(decimal cod, string userName, string Pass, decimal type) {
            return base.Channel.CreateUser(cod, userName, Pass, type);
        }
        
        public System.Threading.Tasks.Task<bool> CreateUserAsync(decimal cod, string userName, string Pass, decimal type) {
            return base.Channel.CreateUserAsync(cod, userName, Pass, type);
        }
        
        public string UpdateUSer(decimal cod, string userName, string Pass, decimal type) {
            return base.Channel.UpdateUSer(cod, userName, Pass, type);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUSerAsync(decimal cod, string userName, string Pass, decimal type) {
            return base.Channel.UpdateUSerAsync(cod, userName, Pass, type);
        }
        
        public WebPortafolio.ServiceCesfam.Usuario ReadUser(decimal cod) {
            return base.Channel.ReadUser(cod);
        }
        
        public System.Threading.Tasks.Task<WebPortafolio.ServiceCesfam.Usuario> ReadUserAsync(decimal cod) {
            return base.Channel.ReadUserAsync(cod);
        }
        
        public bool DeleteUser(decimal id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(decimal id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public bool CrearFuncionario(decimal cod, string nombre, string paterno, string materno, string direccion, decimal telefono) {
            return base.Channel.CrearFuncionario(cod, nombre, paterno, materno, direccion, telefono);
        }
        
        public System.Threading.Tasks.Task<bool> CrearFuncionarioAsync(decimal cod, string nombre, string paterno, string materno, string direccion, decimal telefono) {
            return base.Channel.CrearFuncionarioAsync(cod, nombre, paterno, materno, direccion, telefono);
        }
        
        public bool DeleteFuncionario(decimal id) {
            return base.Channel.DeleteFuncionario(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFuncionarioAsync(decimal id) {
            return base.Channel.DeleteFuncionarioAsync(id);
        }
        
        public bool CrearMedicamento(int id, string nombre, string nomGenerico, System.DateTime fec_vencimiento, string laboratorio) {
            return base.Channel.CrearMedicamento(id, nombre, nomGenerico, fec_vencimiento, laboratorio);
        }
        
        public System.Threading.Tasks.Task<bool> CrearMedicamentoAsync(int id, string nombre, string nomGenerico, System.DateTime fec_vencimiento, string laboratorio) {
            return base.Channel.CrearMedicamentoAsync(id, nombre, nomGenerico, fec_vencimiento, laboratorio);
        }
    }
}
